version: '3.8'

services:

  fb-node:
    container_name: fb-node
    image: node:21.7.1-alpine3.18
    volumes:
      - ./app:/app
      - node-cache:/usr/local/share/.cache
    working_dir: /app

volumes:
  node-cache:
